# configuration
# =============

# device to train the model on
device: ' ' #device: ' ' for cpu, device: '0' for gpu

# dataset configuration
dataset:
  name: 'custom'
  root: 'Data/'
  train_test_split: 0.8

# training process configuration
train:
  batch_size: 5
  pretrained: Trues
  pretrained_folder: 'pretrained'

# inference process configuration
test:
  batch_size: 5
